server:
  port: 8080
  address: 0.0.0.0


spring:

  #==========druid datasource===============
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/tc?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    #==================redis==================
    redis:
      host: localhost
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD}

  #=============mail=============
  mail:
    host: smtp.qq.com
    username: 2125205485@qq.com
    password: ${MAIL_PASSWORD}
    port: 465
    ssl:
      enabled: true

#==============elasticsearch==========================
elasticsearch:
  apiKey: ${ELASTICSEARCH_APIKEY}
  uri: https://localhost:9200
  host: localhost
  port: 9200
  scheme: https

#===============mybatis==================
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.demo.pojo
#==================file==============
file:
  upload:
    avatar-path: ./data/upload/avatar/
    avatar-url-prefix: /avatar/
#logging:
#  level:
#    com.demo: debug
